[package]
name = "aoc2015"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aoc = { version = "0.1.0", path = "../aoc" }
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
md5 = "0.7.0"
